### PR TITLE
Feature/move-dependencies-to-package

### PR DESCRIPTION
**Pull request by tloesch**
- added missing mapboxgl dependency
- replaced bundled threejs library with npm package dependency
- added new dist builds

### CODE REVIEW

**Review by jscastro76 — COMMENTED** [review]
First of all thank you so much for the latest PRs and your interest on improving Threebox.
I could agree with these changes, indeed it was my first idea when I decided to continue evolving Threebox, but in both cases, original Threebox and this fork, the assumption is that it´s a plugin for THREE.js, not a mapbox plugin, that´s why mapbox map is provided as an object reference and used as a member of Threebox instance. 
But there are two more reasons for keeping mapbox ouside Threebox:
-So far, has not been needed at all to include mapbox module and I prefer to keep it as a link in the pages that will use mapbox. 
- Also because of the BSD license from mapbox, I´d discourage to add it to Threebox as part of the solution. 

Regarding THREE as a module, I have identified some issues and breaking changes beyond v1.18, so I think is better to keep it as it´s referenced and liked as a file right now.
Because of all of this, I must reject this PR. If you have an specific requirement for these changes feel free to fork it.

**Comment by tloesch** [comment]
@jscastro76 
First of all, thanks for the fast reviews!

I understand your reasons to not accept this PR.
**So i made changes to it:**

- _Changed the Version from THREE.js to 0.118.0 in the package.json_
- _Removed the mapboxgl dependency and the requires from the files_

Dependency mangement seems much easier to me if you do it centralized (package.json) instead over bundled files.
With this change its way easier to switch between the THREE.js versions and also to see which version is currently loaded.
Hopefully you can now accept the PR.

**Regarding mapboxgl:**
We have a project where we load mapboxgl only as module.
So we dont have global reference for threebox available.
We also dont want to bind modules to the global variable space.

**Solution Suggestion:**
When creating a Threebox instance there should be the possibillty to add the mapboxgl reference via the constructor parameters (as optional).

If you approve this, then i will create a new feature PR for this.

**Comment by tloesch** [comment]
@jscastro76  do you already have some feedback for me?

**Comment by jscastro76** [comment]
> @jscastro76 do you already have some feedback for me?

If we apply this PR we will have a regression on this [bug](https://github.com/jscastro76/threebox/issues/23) among other behaviors detected such as adding a single [Object3D that won’t render properly](https://stackoverflow.com/questions/63382974/three-js-cant-render-cube-on-mapbox-gl-js-custom-webgl-layer#comment112077608_63382974)

Three.js v118 was specially critical as it changed from WebGLRenderer from 1 to 2, they are now in 121 and some of these issues haven’t been solved.

**Comment by tloesch** [comment]
Oh okay. I thought the breaking changes appears beyond v118.
Whats about changing the version to v117?

Or tell me a working and stable version. Then i will adjust this PR to this version.

**Comment by tloesch** [comment]
@jscastro76 reminder for this pr

**Comment by jscastro76** [comment]
After analyzing this deeply, and despite I'd love to have three js moved to a installed dependency, I still have requirements to keep THREE.js bundled due the script must be executed as an standalone resource in a disconnected production environment without any dependency installed, that´s why also suncalc and other modules for the loaders were included. 
As said, thanks for your contributions, but in this case I need to keep three bundled.
Regarding the version, I started this week to check the latest version one of THREE, but some issues still there due to the use of WebGlRenderer 2

**Pull request closed without merging**
