### PR TITLE
Standardize module

### PR DESCRIPTION
**Pull request by juneyon**
Super useful library! I made a few fixes because it wasn't immediately working for me since some of these issues caused it to fail on my environment.

changes:
- fixes whitespace inconsistency (auto-done by editor)
- unbundled ThreeJS + mapbox-gl into package.json dependencies
- fixed test suite to actually be able to run, all pass except one
- babel compatible
- merged utils folders and fixed capitalization inconsistency
- fixed some typos

known issues:
- did not remove calls to mapbox.com-hosted mapbox-gl libraries in examples
- one of the test fails with a precision error but that was already there

### CODE REVIEW

**Comment by jscastro76** [comment]
Hi @juneyon, 
First of all thanks for your contribution, I'd like to know why it was not working on your end as this is being used as is in production environments and by other users since I forked it. 
Reviewing the the PR I could agree with almost all these changes (I could apply them, no problem), I like specially the tests update since I haven't had time to work on it yet. 
But I don't agree on the change of introducing mapbox-gl as part of the bundle. Due to the license restrictions of mapbox, I agreed on the approach from peterqliu of keeping mapbox as an external reference and not as part of the bundle, keeping this as a THREE plugin only for Mapbox. Also in THREE.js due to issue #16 regarding the copy constructor of `Box3Helper`, that is a bug not yet resolved in THREE.js, we cannot add it as part of the packages but as a file with the bug solved. Indeed in your case, if you add it as a module, you should have now a bug in duplicate() method.

**Comment by juneyon** [comment]
> First of all thanks for your contribution, I'd like to know why it was not working on your end as this is being used as is in production environments and by other users since I forked it.
My environment is case sensitive, so some of the relative paths are broken, hence the capitalization fix. And some of the syntax was breaking Babel from applying its transforms.

>But I don't agree on the change of introducing mapbox-gl as part of the bundle.
I unbundled ThreeJS. What I added for mapbox-gl is just a reference, it doesn't repackage it. But it's just as easily removable if you'd like, I didn't really see a need for those references to be there in the first place and I don't use them.

>Also in THREE.js due to issue #16 regarding the copy constructor of Box3Helper, that is a bug not yet resolved in THREE.js, we cannot add it as part of the packages but as a file with the bug solved. Indeed in your case, if you add it as a module, you should have now a bug in duplicate() method.
Wouldn't it be better to fork their repo at v117 to apply the fix as a mitigation? It seems counterintuitive to be using npm for version management yet bundle a compiled module into your repo.

**Comment by jscastro76** [comment]
I have already fixed the case sensitive issue and also the tests, I was about to push the commit up.
Surely it would be better to fork the full THREE.js but just for 5 lines of code I thought it was like shooting a fish in a barrel, and I'm not planning to upgrade to v118, because with an initial test I detected breaking changes due to the change to WebGl2Renderer by default. I'll give it a try again as they have fixed twice the 118.

**Comment by joedjc** [comment]
@jscastro76 @joshnice We agree about not bundling Mapbox with the library. Not sure if this is relevant but we've had some issues getting the library to work in an Angular environment where we install/import mapbox-gl using npm rather than as an html script tag. We were getting errors where threebox seemed to be unable to access mapbox-gl. We're still looking into it as it may be something Angular specific but thought it was worth mentioning. The original threebox library seemed to be ok with this.

**Comment by jscastro76** [comment]
I have pushed a commit 

> @jscastro76 @joshnice We agree about not bundling Mapbox with the library. Not sure if this is relevant but we've had some issues getting the library to work in an Angular environment where we install/import mapbox-gl using npm rather than as an html script tag. We were getting errors where threebox seemed to be unable to access mapbox-gl. We're still looking into it as it may be something Angular specific but thought it was worth mentioning. The original threebox library seemed to be ok with this.

**Comment by jscastro76** [comment]
All these changes have been applied except the bundling, so I’ll close this PR as it’s not being applied completely.
Please check if the latest commit fits your case sensitive needs and renames. Let me know if there’s any issue. Thanks again for contributing, I’m sure now that we share the source there will be more opportunities to collaborate on new features

**Pull request closed without merging**
